"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app --iconfile images/dots.ico --optimize 1
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
  ('images/', ['images/green.png', 'images/splash.png', 'images/blue.png',
               'images/game_over.jpg', 'images/red.png', 'images/yellow.png'],
  ),
]
OPTIONS = {
}

setup(
    name='dots',
    app=APP,
    data_files=DATA_FILES,
    options=OPTIONS,
    setup_requires=['py2app'],
)
